
import Navbar from '../navbar/page'
import Seventhcomponent from '../seventhcomponent/page'
import Footer from '../footer/page'
export const metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
  }
  
   function RootLayout({ children }) {
    return (
     // <html lang="en">
      // <body> 
       <>
            <Navbar/>
          {children}
         
          <Seventhcomponent/>
          <Footer/>
          
       </>
       //   </body>
     // </html>
    )
  }
  export default RootLayout