import './globals.css'
import Navbar from './navbar/page'
import Footer from './footer/page'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> 
        <Navbar/>
        {children} 
        <Footer/>
        </body>
    </html>
  )
}
